apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bloop
  title: K Jasxa
  description: A static HTML website. Just like the good old days.
  links:
    - url: https://RoadieHQ.github.io/bloop/
      title: Live website
  annotations:
    github.com/project-slug: RoadieHQ/bloop
spec:
  type: website
  owner: engineering
  lifecycle: experimental
